export const SET_ACTIVE_BOOK = 'SET_ACTIVE_BOOK';

export const SELECT_BOOK = 'SELECT_BOOK';

export const SIGNALR_STATE_CHANGED = 'SIGNALR_STATE_CHANGED';

export const UPDATE_LIBRARY_STATE = 'UPDATE_LIBRARY_STATE';

